
CREATE TABLE IF NOT EXISTS `CATEGORY` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `TAG` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`)
);

INSERT INTO CATEGORY(NAME) VALUES ('other');
INSERT INTO CATEGORY(NAME) VALUES ('bills');
INSERT INTO CATEGORY(NAME) VALUES ('food');

CREATE TABLE IF NOT EXISTS `EXPENSE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `AMOUNT` decimal(15,2) NOT NULL,
  `SPENT_ON` datetime DEFAULT NULL,
  `TLM` datetime DEFAULT NULL,
  `CATEGORY_ID` bigint(20) NOT NULL DEFAULT '1',
  PRIMARY KEY (`ID`),
  CONSTRAINT `expense_ibfk_1` FOREIGN KEY (`CATEGORY_ID`) REFERENCES `CATEGORY` (`ID`)
);

CREATE TABLE `EXPENSE_TAG` (
  `EXPENSE_ID` bigint(20) NOT NULL,
  `TAG_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`EXPENSE_ID`,`TAG_ID`)
);

INSERT INTO EXPENSE(AMOUNT,SPENT_ON,TLM,CATEGORY_ID) VALUES(8888,'2014-01-01','2014-01-01',1);
INSERT INTO EXPENSE(AMOUNT,SPENT_ON,TLM,CATEGORY_ID) VALUES(7777,'2014-01-02','2014-01-01',1);
INSERT INTO EXPENSE(AMOUNT,SPENT_ON,TLM,CATEGORY_ID) VALUES(6666,'2014-01-01','2014-01-01',1);

INSERT INTO EXPENSE(AMOUNT,SPENT_ON,TLM,CATEGORY_ID) VALUES(5555,'2014-02-01','2014-02-01',1);
INSERT INTO EXPENSE(AMOUNT,SPENT_ON,TLM,CATEGORY_ID) VALUES(4444,'2014-02-02','2014-02-01',2);
INSERT INTO EXPENSE(AMOUNT,SPENT_ON,TLM,CATEGORY_ID) VALUES(3333,'2014-02-01','2014-02-01',3);

INSERT INTO TAG(NAME) VALUES('firstTag');

